### ISSUE TITLE
Add Blur my Shell to extension list

### ISSUE THREAD

**Issue by nuzzle000** [ublue-os/beyond#81]
[https://extensions.gnome.org/extension/3193/blur-my-shell/](url)

Many consider this an essential UI improvement

**Comment by cassidyjames** [comment]
I took a look and there is one place I think it could jive with upstream, which is in the screenshots UI. However, I don't think shipping the entire extension as-is or configured so narrowly makes sense at this point.

On my long personal backlog is to write up some sort of guidelines for when and how blur should be used in GNOME UI, but I haven't gotten around to it. One core part of that, though, is that you should not have a blurred version of something behind itself—like a blurred wallpaper behind the wallpaper—because it doesn’t make spatial sense and just feels like blindly following a trend. This sort of design is most at risk of feeling outdated in a few years. Where blur could make sense—preserving foreground legibility of semi-transparent elements—Blur My Shell doesn’t currently handle super well.
